drop table if exists tbl_todos;

CREATE TABLE tbl_todos (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    task varchar(50) NOT NULL,
    completed boolean NOT NULL DEFAULT false,
    CONSTRAINT tbl_todos_pk PRIMARY KEY (id)
);
